-- liquibase formatted sql
-- changeset anosv:2
create table notification_tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     BIGINT NOT NULL,
    date_time   TIMESTAMP NOT NULL,
    description TEXT NOT NULL
)